install.packages("devtools",dependencies=TRUE)
devtools::install_github("awsm-research/Rnalytica", upgrade="always")
install.packages("ggplot2")
install.packages("car")
install.packages("effects")
install.packages("ScottKnottESD")
install.packages("gridExtra")
install.packages("effsize")
install.packages("rms")
install.packages("C50")
install.packages("randomForest")
install.packages("FFTrees")
install.packages("caret")
install.packages("DMwR")